import type { Metadata } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import { getLocale } from "next-intl/server";

import { A11Y_CONTRAST_KEY, A11Y_FONT_KEY, parseA11yPreferences } from "@/lib/a11y";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Geist-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = localFont({
  src: "./fonts/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  // T2.8 Part 1：替换 create-next-app 占位（原 "Create Next App" / "Generated by create next app"）
  // TODO(T2.8+)：改读 Config（group='site' 的 `site.name` / `seo.home.*`）——需改用 generateMetadata，
  //   且会给每条路由的 metadata 生成各加一次查询；见 docs/00 §8 #55
  title: {
    default: "XX大学",
    template: "%s | XX大学",
  },
  description: "XX大学官方网站",
  applicationName: "XX大学",
  keywords: ["XX大学", "官方网站", "新闻", "招生", "科研"],
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // docs/15 §1 / §3.1：<html lang> 随请求 locale 变化（默认 zh，非默认语言 URL 带 /en 前缀）。
  // 根 layout 继续持有 <html>/<body>（U-B 裁决）；[locale] 段只负责 provider 与静态渲染标记。
  const locale = await getLocale();

  // M5-2a · 无障碍偏好改由 **cookie** 驱动（取代 T1.3/T2.3 的 localStorage + 内联脚本）
  // ----------------------------------------------------------------------------
  // ① 读：本层（Server Component）用 `next/headers` 的 `cookies()` 取两个偏好；
  //    `parseA11yPreferences()` 是**纯函数**（校验白名单 + 非法回落默认值）
  // ② 写：客户端切换时由 `@/lib/a11y` 的 `set()` 写同一个 cookie（键名见 A11Y_*_KEY）
  // ③ 渲染：档位**直接写进 `<html>` 的 SSR 属性** ⇒ 首帧即正确（**零闪烁**），
  //    因此**不再需要"首帧前改写属性"的内联脚本**
  //
  // 为什么删脚本：旧方案始终会渲染一个 `<script>`，React 19 报
  //   「Encountered a script tag while rendering React component」（`docs/00` §8 #51）；
  //   `next/script` + `beforeInteractive` 也没能消除该警告 ⇒ 改用 cookie 根治。
  //
  // 已知取舍（M5-2a 裁决）：cookie **不触发 `storage` 事件** ⇒ 跨标签页实时同步不再具备；
  //   旧 localStorage 值**不迁移**（重新选一次即可）。详见 `@/lib/a11y` 模块头注释。
  const cookieStore = await cookies();
  const a11y = parseA11yPreferences({
    fontScale: cookieStore.get(A11Y_FONT_KEY)?.value,
    contrast: cookieStore.get(A11Y_CONTRAST_KEY)?.value,
  });

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-a11y-font={a11y.font}
      data-a11y-contrast={a11y.contrast}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
