import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { A11Y_INIT_SCRIPT } from "@/lib/a11y";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  // T1.3 · 无障碍偏好的 SSR 默认属性 + 防 FOUC 内联脚本
  //   · data-a11y-font / data-a11y-contrast 的默认值必须等于 @/lib/a11y 的
  //     DEFAULT_FONT_SCALE / DEFAULT_CONTRAST（内联脚本的回落值也是它们）
  //   · 内联脚本在 <head> 中同步执行，早于首次绘制；localStorage 有值时会把
  //     这两个属性改写成用户档位 → <html> 需要 suppressHydrationWarning
  //     （官方依据：next/dist/docs/01-app/02-guides/preventing-flash-before-hydration.md）
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-a11y-font="100"
      data-a11y-contrast="off"
      suppressHydrationWarning
    >
      {/* 防 FOUC：读 localStorage 并把档位写回 <html>（脚本内容见 @/lib/a11y） */}
      <head>
        <script dangerouslySetInnerHTML={{ __html: A11Y_INIT_SCRIPT }} />
      </head>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
